version: '3'
####
# !! remember define RSERVE_NODE_NUM in .env or as environment variable
####

services:

  proxy:
    container_name: rcloud
    expose:
      - "6311"
    build:
      context: .
      dockerfile: Dockerfile-proxy
      args:
        BUILDTIME_RSERVE_NODE_NUM: ${RSERVE_NODE_NUM}
    ports:
      - "6311:6311"

  rserve:
    image: ubcctlt/rserve
    # if you are using "docker-compose up"to start multiple Rserve containers,
    # add "--compatibility" flag so the "deploy" section works
    deploy:
      mode: replicated
      replicas: ${RSERVE_NODE_NUM}