FROM alpine as builder

# the wstunnel docker image on docker hub is outdated.
# getting the version 3 directly from github
RUN cd /tmp && \
    apk update && \
    apk add wget && \
    wget https://github.com/erebe/wstunnel/releases/download/v3.0/wstunnel-linux-x64.zip && \
    unzip wstunnel-linux-x64.zip


FROM alpine as runner

WORKDIR /root
COPY --from=builder /tmp/wstunnel .
RUN chmod a+x ./wstunnel

CMD ["/root/wstunnel"]
