FROM nginx:1.17

ARG BUILDTIME_RSERVE_NODE_NUM=2
ENV RSERVE_NODE_NUM=${BUILDTIME_RSERVE_NODE_NUM}

COPY conf/nginx.conf /tmp/nginx.conf

EXPOSE 8080

# add upstream servers to nginx conf file
RUN awk -v node_count=${RSERVE_NODE_NUM} -F\n '/## Define rserve nodes here/ {for(i=1;i<=node_count;i++) print "server docker-r-cluster_rserve_"i":8000 max_fails=3 fail_timeout=60s;"; next} 1' /tmp/nginx.conf > /etc/nginx/conf.d/default.conf

RUN rm /tmp/nginx.conf
